### ISSUE TITLE
eureca.js?

### ISSUE THREAD

**Issue by MStumpp** [Ezelia/eureca#1]
I am having problems finding the "eureca.js" script to be used on the client.

<script src="/eureca.js"></script>

Where can I find it?

**Comment by alaa-eddine** [comment]
hello
this script is generated on the fly and mapped to /eureca.js the goal is to
keep everything working seamlessly .

Just add this line to your <head> section :

<script src="/eureca.js" ></script>


that's all :)

tell me if you still have problems.

regards.

**Comment by MStumpp** [comment]
ok, works... thanks

**Comment by magicmike** [comment]
I also wondered this, and on the first example in the home page, get the error:
    ReferenceError: Eureca is not defined
         var client = new Eureca.Client();

Which suggests that it can't find it. Any ideas?

**Comment by alaa-eddine** [comment]
Hi @magicmike ,
have you added the following line to the HTML document head ?

``` javascript
<script src="/eureca.js" ></script>
```

**Comment by alaa-eddine** [comment]
also please note that this version is very old and no more supported.
please use this instead ===> https://github.com/Ezelia/eureca.io

**Comment by magicmike** [comment]
Yep, added that line HTML to document head. Continued on new thread. 
https://github.com/Ezelia/eureca.io/issues/16
