### ISSUE TITLE
UDP support via webRTC

### ISSUE THREAD

**Issue by fyyyyy** [Ezelia/eureca#3]
Hello

Do you think its possible to support UDP via webRTC or similar ?

For high CCU realtime games UDP is much preferable to TCP

Cheers

**Comment by alaa-eddine** [comment]
eureca is deprecated, please use eureca.io (https://github.com/Ezelia/eureca.io) 
which have webRTC support with UDP .
see the example here for webRTC usage : https://github.com/Ezelia/eureca.io/tree/master/examples/7-webrtc

please note that nodejs server side WebRTC is supported throught node-webrtc which only work on linux right now, so the server should be in linux, but the client can be on any platform.

**Comment by fyyyyy** [comment]
awesome, thanks :+1: 
eureca.io should get more attention imo. google search however doesnt bring it up when looking for multiplayer html5

**Comment by alaa-eddine** [comment]
yeah it maybe lack some SEO, but if you look for "multiplayer HTML5 tutorial" you'll find a great tutorial I made at the third position : http://ezelia.com/2014/tutorial-creating-basic-multiplayer-game-phaser-eureca-io

at Ezelia we implemented a flexible multiplayer server based on eureca.io and we are thinking to open source it, but it will require a lot of documentation and API work ... and we don't have enougth time right now. 

btw, if you have any project using eureca.io and want to speak about your experience I'll be glad to feature it on http://ezelia.com :)
